"""grep: BSD grep 2.6.0-FreeBSD."""

from case import UTF8, Case

BINARY = "/usr/bin/grep"

CASES = [
    # Basic matching and output selection.
    Case("literal", ["beta", "in.txt"]),
    Case("no-match-status", ["zzz", "in.txt"]),
    Case("missing-file", ["beta", "missing.txt"]),
    Case("missing-file-silent", ["-s", "beta", "missing.txt"]),
    Case("two-files", ["beta", "in.txt", "words.txt"]),
    Case("with-filename", ["-H", "beta", "in.txt"]),
    Case("no-filename", ["-h", "beta", "in.txt", "words.txt"]),
    Case("line-number", ["-n", "beta", "in.txt"]),
    Case("byte-offset", ["-b", "beta", "in.txt"]),
    Case("count", ["-c", "beta", "in.txt", "words.txt"]),
    Case("count-invert", ["-vc", "beta", "in.txt"]),
    Case("invert", ["-v", "beta", "in.txt"]),
    Case("ignore-case", ["-i", "BETA", "words.txt"]),
    Case("ignore-case-y", ["-y", "BETA", "words.txt"]),
    Case("word", ["-w", "gam", "words.txt"]),
    Case("word-match", ["-w", "beta", "words.txt"]),
    Case("line", ["-x", "beta", "words.txt"]),
    Case("only-matching", ["-o", "b.ta", "words.txt"]),
    Case("only-matching-multi", ["-on", "a", "in.txt"]),
    Case("max-count", ["-m", "1", "beta", "words.txt"]),
    Case("max-count-context", ["-m", "1", "-A", "1", "beta", "words.txt"]),
    Case("quiet-match", ["-q", "beta", "in.txt"]),
    Case("quiet-nomatch", ["-q", "zzz", "in.txt"]),
    Case("files-with-matches", ["-l", "beta", "in.txt", "words.txt", "empty.txt"]),
    Case("files-without-match", ["-L", "beta", "in.txt", "words.txt", "empty.txt"]),
    Case("null-after-name", ["--null", "-l", "beta", "in.txt", "words.txt"]),
    Case("label-stdin", ["--label=piped", "-H", "beta"], stdin="in.txt"),
    # Pattern syntax and sources.
    Case("basic-regex", ["-G", "be*ta", "words.txt"]),
    Case("basic-interval", ["a\\{2\\}", "words.txt"]),
    Case("basic-backref", ["\\(a\\)\\1", "words.txt"]),
    Case("extended-alternation", ["-E", "al(ph|xx)a|gamma", "words.txt"]),
    Case("extended-plus", ["-E", "e+t", "words.txt"]),
    Case("extended-class", ["-E", "^[[:upper:]][[:alpha:]]+$", "words.txt"]),
    Case("fixed-strings", ["-F", "a.b", "words.txt"]),
    Case("fixed-multi", ["-F", "-e", "alpha", "-e", "delta", "words.txt"]),
    Case("multiple-e", ["-e", "alpha", "-e", "^gamma", "words.txt"]),
    Case("pattern-file", ["-f", "patterns.txt", "words.txt"]),
    Case("pattern-file-empty", ["-f", "empty.txt", "words.txt"]),
    Case("empty-pattern", ["", "in.txt"]),
    Case("anchors", ["^beta$", "words.txt"]),
    Case("invalid-regex", ["-E", "a(b", "in.txt"]),
    Case("dash-pattern", ["-e", "-x", "words.txt"]),
    # Context.
    Case("after", ["-A", "1", "alpha", "words.txt"]),
    Case("before", ["-B", "2", "delta", "words.txt"]),
    Case("context", ["-C", "1", "gamma", "words.txt"]),
    Case("context-numeric", ["-1", "gamma", "words.txt"]),
    Case("context-separators", ["-n", "-A", "1", "a", "words.txt"]),
    # Colour.
    Case("color-always", ["--color=always", "beta", "words.txt"]),
    Case("color-never", ["--color=never", "beta", "words.txt"]),
    Case("color-env", ["--color=always", "beta", "words.txt"],
         env={"GREP_COLOR": "01;32"}),
    Case("color-only", ["--color=always", "-o", "e", "in.txt"]),
    # Input shapes.
    Case("stdin", ["beta"], stdin="in.txt"),
    Case("stdin-dash", ["beta", "-"], stdin="in.txt"),
    Case("stdin-count", ["-c", "a"], stdin="words.txt"),
    Case("empty-file", ["beta", "empty.txt"]),
    Case("no-trailing-newline", ["tail", "noeol.txt"]),
    Case("crlf", ["-c", "line", "crlf.txt"]),
    Case("long-line", ["-c", "needle", "long.txt"]),
    Case("large-file", ["-c", "99999", "big.txt"]),
    Case("large-file-n", ["-n", "^1999[0-9]9$", "big.txt"]),
    Case("binary-default", ["payload", "binary.bin"]),
    Case("binary-text", ["-a", "payload", "binary.bin"]),
    Case("binary-ignore", ["-I", "payload", "binary.bin"]),
    Case("binary-files-without", ["--binary-files=without-match", "payload", "binary.bin"]),
    Case("null-data", ["-z", "two", "nul.txt"]),
    Case("mmap", ["--mmap", "beta", "in.txt"]),
    Case("line-buffered", ["--line-buffered", "beta", "in.txt"]),
    Case("unreadable", ["beta", "unreadable.txt"]),
    # Directories and recursion.
    Case("directory-arg", ["beta", "tree"]),
    Case("directory-skip", ["-d", "skip", "beta", "tree"]),
    Case("directory-read", ["-d", "read", "beta", "tree"]),
    Case("recursive", ["-r", "beta", "tree"]),
    Case("recursive-n", ["-rn", "beta", "tree"]),
    Case("recursive-l", ["-rl", "beta", "tree"]),
    Case("recursive-count", ["-rc", "beta", "tree"]),
    Case("recursive-include", ["-r", "--include=*.c", "beta", "tree"]),
    Case("recursive-exclude", ["-r", "--exclude=*.log", "beta", "tree"]),
    Case("recursive-exclude-dir", ["-r", "--exclude-dir=deep", "beta", "tree"]),
    Case("recursive-follow-all", ["-R", "-S", "beta", "tree"]),
    Case("recursive-no-follow", ["-R", "-p", "beta", "tree"]),
    Case("recursive-cwd", ["-r", "gamma", "."]),
    Case("devices-skip", ["-D", "skip", "beta", "-"], stdin="in.txt"),
    # Compressed input.
    Case("gzip", ["-Z", "beta", "in.txt.gz"]),
    Case("bzip2", ["-J", "beta", "in.txt.bz2"], tags={"compression"}),
    Case("xz", ["-X", "beta", "in.txt.xz"], tags={"compression"}),
    Case("lzma", ["-M", "beta", "in.txt.lzma"], tags={"compression"}),
    # Locales.
    Case("utf8-dot", ["-o", "caf.", "utf8.txt"], env=UTF8),
    Case("utf8-ignore-case", ["-i", "ÜBER", "utf8.txt"], env=UTF8),
    Case("utf8-class", ["-o", "[[:alpha:]]*ve", "utf8.txt"], env=UTF8),
    Case("utf8-invalid-bytes", ["-c", "x", "latin1.txt"], env=UTF8),
    Case("c-locale-bytes", ["-o", "caf.", "utf8.txt"]),
    # Diagnostics and usage.
    Case("version", ["-V"]),
    Case("help", ["--help"]),
    Case("bad-option", ["--definitely-not-an-option", "x", "in.txt"]),
    Case("no-pattern", []),
    Case("bad-context", ["-A", "lots", "x", "in.txt"]),
]
